/* ============================================================
   MTG Card Scanner — Scan List prices

   Adds Card Kingdom / Star City Games pricing to the existing
   Scan List without changing the internal collection logic.

   Requirements:
   - app.js must load before this file.
   - batch-identify.js may load before this file.
   - data/prices.json is generated by scripts/build_prices.py.
============================================================ */

"use strict";


/* ============================================================
   CONFIG
============================================================ */

const PRICE_DATA_URL =
  "data/prices.json";


const PRICE_FINISH_MAP = {
  nonfoil: "normal",
  foil: "foil",
  etched: "etched"
};


/* ============================================================
   STATE
============================================================ */

let priceDatabase = null;
let priceLoading = false;
let priceLoadError = null;


/* ============================================================
   BASIC HELPERS
============================================================ */

function priceMoney(
  value
) {

  const number =
    Number(
      value
    );


  if (
    !Number.isFinite(
      number
    )
  ) {

    return "N/D";
  }


  return (
    "$" +
    number.toFixed(
      2
    )
  );
}


function priceNumberForCsv(
  value
) {

  const number =
    Number(
      value
    );


  if (
    !Number.isFinite(
      number
    )
  ) {

    return "";
  }


  return number.toFixed(
    2
  );
}


function priceCsvCell(
  value
) {

  const text =
    value == null
      ? ""
      : String(
          value
        );


  return /[",\n]/.test(
    text
  )
    ? '"' +
      text.replace(
        /"/g,
        '""'
      ) +
      '"'
    : text;
}


function priceToCsv(
  rows
) {

  return rows
    .map(
      (row) =>
        row
          .map(
            priceCsvCell
          )
          .join(
            ","
          )
    )
    .join(
      "\r\n"
    );
}


function getEntryFinish(
  entry
) {

  if (
    entry?.finish
  ) {

    return entry.finish;
  }


  return entry?.foil
    ? "foil"
    : "nonfoil";
}


function getEntryFinishLabel(
  entry
) {

  const finish =
    getEntryFinish(
      entry
    );


  const labels = {
    nonfoil: "Non-foil",
    foil: "Foil",
    etched: "Etched Foil",
    surgefoil: "Surge Foil",
    galaxyfoil: "Galaxy Foil",
    textured: "Textured Foil",
    review: "Other / Review"
  };


  return (
    labels[
      finish
    ] ||
    finish ||
    "Unknown"
  );
}


/* ============================================================
   PRICE LOOKUP
============================================================ */

function getEntryPrice(
  entry,
  provider
) {

  if (
    !priceDatabase ||
    !entry?.card?.id
  ) {

    return null;
  }


  const finish =
    getEntryFinish(
      entry
    );


  const priceFinish =
    PRICE_FINISH_MAP[
      finish
    ];


  /*
    Special finishes are intentionally NOT mapped to regular foil.
    We prefer N/D over showing a potentially incorrect price.
  */
  if (
    !priceFinish
  ) {

    return null;
  }


  const cardPrices =
    priceDatabase.cards?.[
      entry.card.id
    ];


  const providerPrices =
    cardPrices?.[
      provider
    ];


  const point =
    providerPrices?.[
      priceFinish
    ];


  const value =
    Number(
      point?.price
    );


  if (
    !Number.isFinite(
      value
    )
  ) {

    return null;
  }


  return {
    price:
      value,

    date:
      point?.date ||
      null,

    currency:
      providerPrices?.currency ||
      "USD"
  };
}


function getProviderTotal(
  provider
) {

  let total = 0;
  let pricedLines = 0;


  const totalLines =
    collected.length;


  collected.forEach(
    (entry) => {

      const point =
        getEntryPrice(
          entry,
          provider
        );


      if (
        !point
      ) {

        return;
      }


      const qty =
        Math.max(
          1,
          Number(
            entry.qty
          ) ||
          1
        );


      total +=
        point.price *
        qty;


      pricedLines +=
        1;
    }
  );


  return {
    total,
    pricedLines,
    totalLines,
    complete:
      totalLines > 0 &&
      pricedLines ===
        totalLines
  };
}


function formatProviderTotal(
  provider
) {

  const result =
    getProviderTotal(
      provider
    );


  if (
    result.totalLines === 0
  ) {

    return "$0.00";
  }


  if (
    result.pricedLines === 0
  ) {

    return "N/D";
  }


  const amount =
    priceMoney(
      result.total
    );


  if (
    result.complete
  ) {

    return amount;
  }


  return (
    amount +
    ` · ${result.pricedLines}/${result.totalLines} priced`
  );
}


/* ============================================================
   PRICE DATABASE
============================================================ */

async function loadPriceDatabase(
  force = false
) {

  if (
    priceLoading
  ) {

    return false;
  }


  if (
    priceDatabase &&
    !force
  ) {

    return true;
  }


  priceLoading =
    true;


  priceLoadError =
    null;


  syncPriceControls();
  renderPriceSummary();


  try {

    const url =
      force
        ? `${PRICE_DATA_URL}?refresh=${Date.now()}`
        : PRICE_DATA_URL;


    const response =
      await fetch(
        url,
        {
          cache:
            force
              ? "no-store"
              : "default"
        }
      );


    if (
      !response.ok
    ) {

      throw new Error(
        `HTTP ${response.status}`
      );
    }


    const data =
      await response.json();


    if (
      !data ||
      typeof data !==
        "object" ||
      !data.cards ||
      typeof data.cards !==
        "object"
    ) {

      throw new Error(
        "Invalid price database"
      );
    }


    priceDatabase =
      data;


    priceLoadError =
      null;


    renderPriceUI();


    return true;

  } catch (
    error
  ) {

    console.error(
      "Price database load failed:",
      error
    );


    priceLoadError =
      error;


    renderPriceUI();


    return false;

  } finally {

    priceLoading =
      false;


    syncPriceControls();
    renderPriceSummary();
  }
}


/* ============================================================
   UX SETUP
============================================================ */

function installPriceStyles() {

  if (
    document.getElementById(
      "scanListPriceStyles"
    )
  ) {

    return;
  }


  const style =
    document.createElement(
      "style"
    );


  style.id =
    "scanListPriceStyles";


  style.textContent = `
    .collection-actions {
      gap: 8px;
      flex-wrap: wrap;
    }

    #refreshPricesBtn {
      margin-right: auto;
    }

    .price-cell,
    .price-head {
      text-align: right;
      font-family: var(--font-mono);
    }

    .price-cell {
      font-size: 12px;
    }

    .price-na {
      color: var(--faint);
    }

    .scan-list-value {
      margin-top: 14px;
      padding: 13px;
      border: 1px solid var(--line-2);
      border-radius: 10px;
      background: var(--panel-2);
    }

    .scan-list-value-title {
      margin-bottom: 9px;
      font-size: 12px;
      font-weight: 700;
      color: var(--muted);
      text-transform: uppercase;
      letter-spacing: .05em;
    }

    .scan-list-value-row {
      display: flex;
      align-items: baseline;
      justify-content: space-between;
      gap: 12px;
      padding: 5px 0;
    }

    .scan-list-value-label {
      font-size: 13px;
      color: var(--muted);
    }

    .scan-list-value-amount {
      text-align: right;
      font-family: var(--font-mono);
      font-size: 14px;
      font-weight: 700;
      color: var(--text);
    }

    .scan-list-price-meta {
      margin-top: 9px;
      padding-top: 9px;
      border-top: 1px solid var(--line);
      font-size: 11px;
      line-height: 1.45;
      color: var(--faint);
    }

    #priceListExportBtn {
      border-color: var(--accent);
    }
  `;


  document.head.appendChild(
    style
  );
}


function renameCollectionUX() {

  const section =
    document.querySelector(
      '[data-app-section="collection"]'
    );


  const title =
    section?.querySelector(
      ".section-title"
    );


  if (
    title
  ) {

    title.textContent =
      "📋 Scan List";
  }
}


function ensurePriceHeaders() {

  const row =
    document.querySelector(
      "#table thead tr"
    );


  if (
    !row ||
    row.querySelector(
      ".price-head"
    )
  ) {

    return;
  }


  const ck =
    document.createElement(
      "th"
    );


  ck.className =
    "price-head";


  ck.textContent =
    "CK";


  ck.title =
    "Card Kingdom price";


  const scg =
    document.createElement(
      "th"
    );


  scg.className =
    "price-head";


  scg.textContent =
    "SCG";


  scg.title =
    "Star City Games price";


  const removeHead =
    row.lastElementChild;


  row.insertBefore(
    ck,
    removeHead
  );


  row.insertBefore(
    scg,
    removeHead
  );
}


function ensurePriceSummary() {

  if (
    document.getElementById(
      "scanListValue"
    )
  ) {

    return;
  }


  const actions =
    document.querySelector(
      ".collection-actions"
    );


  if (
    !actions
  ) {

    return;
  }


  const summary =
    document.createElement(
      "div"
    );


  summary.id =
    "scanListValue";


  summary.className =
    "scan-list-value";


  summary.innerHTML = `
    <div class="scan-list-value-title">
      Scan List Value
    </div>

    <div class="scan-list-value-row">
      <span class="scan-list-value-label">
        Card Kingdom
      </span>

      <span
        id="cardKingdomTotal"
        class="scan-list-value-amount"
      >
        —
      </span>
    </div>

    <div class="scan-list-value-row">
      <span class="scan-list-value-label">
        Star City Games
      </span>

      <span
        id="starCityGamesTotal"
        class="scan-list-value-amount"
      >
        —
      </span>
    </div>

    <div
      id="priceMeta"
      class="scan-list-price-meta"
    >
      Prices have not been loaded yet.
    </div>
  `;


  actions.parentNode.insertBefore(
    summary,
    actions
  );
}


function ensureRefreshButton() {

  if (
    document.getElementById(
      "refreshPricesBtn"
    )
  ) {

    return;
  }


  const actions =
    document.querySelector(
      ".collection-actions"
    );


  if (
    !actions
  ) {

    return;
  }


  const button =
    document.createElement(
      "button"
    );


  button.id =
    "refreshPricesBtn";


  button.className =
    "ghost";


  button.type =
    "button";


  button.textContent =
    "Refresh prices";


  button.addEventListener(
    "click",
    async () => {

      setStatus(
        "Refreshing prices…"
      );


      const ok =
        await loadPriceDatabase(
          true
        );


      setStatus(
        ok
          ? "Prices refreshed."
          : "Could not refresh prices."
      );
    }
  );


  actions.insertBefore(
    button,
    actions.firstChild
  );
}


function ensurePriceExportButton() {

  if (
    document.getElementById(
      "priceListExportBtn"
    )
  ) {

    return;
  }


  const exports =
    document.querySelector(
      ".exports"
    );


  if (
    !exports
  ) {

    return;
  }


  const button =
    document.createElement(
      "button"
    );


  button.id =
    "priceListExportBtn";


  button.type =
    "button";


  button.textContent =
    "Price List CSV";


  button.addEventListener(
    "click",
    exportPriceListCsv
  );


  exports.appendChild(
    button
  );
}


/* ============================================================
   RENDER PRICES IN SCAN LIST
============================================================ */

function createPriceCell(
  entry,
  provider
) {

  const td =
    document.createElement(
      "td"
    );


  td.className =
    "price-cell";


  if (
    !priceDatabase
  ) {

    td.textContent =
      "—";


    td.classList.add(
      "price-na"
    );


    return td;
  }


  const point =
    getEntryPrice(
      entry,
      provider
    );


  if (
    !point
  ) {

    td.textContent =
      "N/D";


    td.classList.add(
      "price-na"
    );


    const finish =
      getEntryFinish(
        entry
      );


    if (
      !PRICE_FINISH_MAP[
        finish
      ]
    ) {

      td.title =
        "No safe price mapping for this finish.";
    }


    return td;
  }


  td.textContent =
    priceMoney(
      point.price
    );


  if (
    point.date
  ) {

    td.title =
      `Price date: ${point.date}`;
  }


  return td;
}


function renderPriceColumns() {

  ensurePriceHeaders();


  const rows =
    Array.from(
      document.querySelectorAll(
        "#tbody tr"
      )
    );


  rows.forEach(
    (row, index) => {

      row
        .querySelectorAll(
          ".price-cell"
        )
        .forEach(
          (cell) =>
            cell.remove()
        );


      const entry =
        collected[
          index
        ];


      if (
        !entry
      ) {

        return;
      }


      const removeCell =
        row.lastElementChild;


      row.insertBefore(
        createPriceCell(
          entry,
          "cardkingdom"
        ),
        removeCell
      );


      row.insertBefore(
        createPriceCell(
          entry,
          "starcitygames"
        ),
        removeCell
      );
    }
  );
}


function renderPriceSummary() {

  ensurePriceSummary();


  const ckTotal =
    document.getElementById(
      "cardKingdomTotal"
    );


  const scgTotal =
    document.getElementById(
      "starCityGamesTotal"
    );


  const meta =
    document.getElementById(
      "priceMeta"
    );


  if (
    ckTotal
  ) {

    ckTotal.textContent =
      priceDatabase
        ? formatProviderTotal(
            "cardkingdom"
          )
        : "—";
  }


  if (
    scgTotal
  ) {

    scgTotal.textContent =
      priceDatabase
        ? formatProviderTotal(
            "starcitygames"
          )
        : "—";
  }


  if (
    !meta
  ) {

    return;
  }


  if (
    priceLoading
  ) {

    meta.textContent =
      "Loading price database…";


    return;
  }


  if (
    priceLoadError
  ) {

    meta.textContent =
      "Prices unavailable. Use Refresh prices to try again.";


    return;
  }


  if (
    !priceDatabase
  ) {

    meta.textContent =
      "Prices load when Scan List is opened.";


    return;
  }


  const generated =
    priceDatabase.meta?.generated_at;


  const source =
    priceDatabase.meta?.cardkingdom_source ||
    "MTGJSON";


  const dateText =
    generated
      ? new Date(
          generated
        ).toLocaleString()
      : "Unknown date";


  meta.textContent =
    `Card Kingdom source: ${source} · Updated: ${dateText} · ` +
    "SCG remains N/D until an authorized source is connected.";
}


function syncPriceControls() {

  const refresh =
    document.getElementById(
      "refreshPricesBtn"
    );


  if (
    refresh
  ) {

    refresh.disabled =
      priceLoading;


    refresh.textContent =
      priceLoading
        ? "Refreshing…"
        : "Refresh prices";
  }


  const exportButton =
    document.getElementById(
      "priceListExportBtn"
    );


  if (
    exportButton
  ) {

    exportButton.disabled =
      priceLoading;
  }
}


function renderPriceUI() {

  renameCollectionUX();
  ensurePriceHeaders();
  ensurePriceSummary();
  ensureRefreshButton();
  ensurePriceExportButton();

  renderPriceColumns();
  renderPriceSummary();
  syncPriceControls();
}


/* ============================================================
   PRICE CSV EXPORT
============================================================ */

async function exportPriceListCsv() {

  if (
    collected.length === 0
  ) {

    setStatus(
      "Nothing to export yet."
    );


    return;
  }


  if (
    !priceDatabase
  ) {

    setStatus(
      "Loading prices before export…"
    );


    const ok =
      await loadPriceDatabase();


    if (
      !ok
    ) {

      setStatus(
        "Price List CSV could not be created because prices are unavailable."
      );


      return;
    }
  }


  const header = [
    "Name",
    "Set",
    "Collector Number",
    "Quantity",
    "Finish",
    "Card Kingdom Price",
    "Card Kingdom Total",
    "Star City Games Price",
    "Star City Games Total"
  ];


  let ckGrandTotal = 0;
  let scgGrandTotal = 0;


  const rows =
    collected.map(
      (entry) => {

        const qty =
          Math.max(
            1,
            Number(
              entry.qty
            ) ||
            1
          );


        const ck =
          getEntryPrice(
            entry,
            "cardkingdom"
          );


        const scg =
          getEntryPrice(
            entry,
            "starcitygames"
          );


        const ckTotal =
          ck
            ? ck.price *
              qty
            : null;


        const scgTotal =
          scg
            ? scg.price *
              qty
            : null;


        if (
          ckTotal != null
        ) {

          ckGrandTotal +=
            ckTotal;
        }


        if (
          scgTotal != null
        ) {

          scgGrandTotal +=
            scgTotal;
        }


        return [
          entry.card?.name ||
            "Unknown Card",

          (
            entry.card?.set ||
            ""
          ).toUpperCase(),

          entry.card?.collector_number ||
            "",

          qty,

          getEntryFinishLabel(
            entry
          ),

          ck
            ? priceNumberForCsv(
                ck.price
              )
            : "",

          ckTotal != null
            ? priceNumberForCsv(
                ckTotal
              )
            : "",

          scg
            ? priceNumberForCsv(
                scg.price
              )
            : "",

          scgTotal != null
            ? priceNumberForCsv(
                scgTotal
              )
            : ""
        ];
      }
    );


  const ckCoverage =
    getProviderTotal(
      "cardkingdom"
    );


  const scgCoverage =
    getProviderTotal(
      "starcitygames"
    );


  const totalQty =
    collected.reduce(
      (
        total,
        entry
      ) =>
        total +
        Math.max(
          1,
          Number(
            entry.qty
          ) ||
          1
        ),
      0
    );


  rows.push([
    "TOTAL",
    "",
    "",
    totalQty,
    "",
    "",
    ckCoverage.pricedLines
      ? priceNumberForCsv(
          ckGrandTotal
        )
      : "",
    "",
    scgCoverage.pricedLines
      ? priceNumberForCsv(
          scgGrandTotal
        )
      : ""
  ]);


  const csv =
    priceToCsv([
      header,
      ...rows
    ]);


  const blob =
    new Blob(
      [
        "\uFEFF",
        csv
      ],
      {
        type:
          "text/csv;charset=utf-8"
      }
    );


  const anchor =
    document.getElementById(
      "dl"
    ) ||
    document.createElement(
      "a"
    );


  const url =
    URL.createObjectURL(
      blob
    );


  anchor.href =
    url;


  anchor.download =
    "scan_list_prices.csv";


  anchor.click();


  setTimeout(
    () =>
      URL.revokeObjectURL(
        url
      ),
    2000
  );


  setStatus(
    `Exported ${collected.length} line(s) → scan_list_prices.csv`
  );
}


/* ============================================================
   HOOK EXISTING RENDER LIST
============================================================ */

const originalRenderList =
  renderList;


renderList =
  function () {

    originalRenderList();
    renderPriceUI();
  };


/* ============================================================
   LAZY LOAD WHEN SCAN LIST OPENS
============================================================ */

const scanListSection =
  document.querySelector(
    '[data-app-section="collection"]'
  );


const scanListToggle =
  scanListSection?.querySelector(
    ".section-toggle"
  );


scanListToggle
  ?.addEventListener(
    "click",
    () => {

      setTimeout(
        () => {

          if (
            scanListSection.classList.contains(
              "open"
            )
          ) {

            loadPriceDatabase();
          }
        },
        0
      );
    }
  );


/* ============================================================
   CLEAR LIST UX TEXT
============================================================ */

const clearScanListButton =
  document.getElementById(
    "clearListBtn"
  );


clearScanListButton
  ?.addEventListener(
    "click",
    () => {

      const hadCards =
        collected.length > 0;


      setTimeout(
        () => {

          if (
            hadCards &&
            collected.length === 0
          ) {

            setStatus(
              "Scan List cleared."
            );
          }
        },
        0
      );
    }
  );


/* ============================================================
   INITIALIZE
============================================================ */

installPriceStyles();
renderPriceUI();