/*
  ============================================================
  MTG Collection Manager
  Cloudflare Worker — Gemini Vision Proxy
  ============================================================

  FEATURES

  - POST /identify
      Identifies one MTG card.

  - POST /identify-batch
      Identifies multiple numbered MTG cards from one contact
      sheet generated by the frontend.

  - GET /health
      Shows Worker status and configured Gemini model chain.

  - Gemini automatic fallback:
      Primary
        ↓
      retry primary once on temporary failure
        ↓
      fallback model 1
        ↓
      fallback model 2

  Required Cloudflare variables / secrets:

    GEMINI_API_KEY
      Secret

    APP_TOKEN
      Secret

    ALLOWED_ORIGIN
      Variable
      Example:
      https://cloukuta.github.io

    GEMINI_MODEL
      Variable
      Recommended:
      gemini-3.5-flash-lite

  Optional variables:

    GEMINI_FALLBACK_MODEL
      Recommended:
      gemini-3.5-flash

    GEMINI_FALLBACK_MODEL_2
      Recommended:
      gemini-3.6-flash

    RATE_LIMITER
      Optional Cloudflare Rate Limiting binding.

  ============================================================
*/


/* ============================================================
   CONFIG
============================================================ */

const DEFAULT_PRIMARY_MODEL =
  "gemini-3.5-flash-lite";


const DEFAULT_FALLBACK_MODEL =
  "gemini-3.5-flash";


const DEFAULT_FALLBACK_MODEL_2 =
  "gemini-3.6-flash";


const SINGLE_TIMEOUT_MS =
  35000;


const BATCH_TIMEOUT_MS =
  60000;


const MAX_IMAGE_BYTES =
  10 * 1024 * 1024;


const PRIMARY_RETRY_DELAY_MS =
  700;


/* ============================================================
   SINGLE CARD PROMPT
============================================================ */

const SINGLE_PROMPT = `
You are identifying ONE Magic: The Gathering card from a photo.

Your most important job is identifying the EXACT PRINTING.

PRIORITY:

1. Read the SET CODE from the bottom information line.
2. Read the COLLECTOR NUMBER.
3. Read the card name when possible.
4. Read the printed language when possible.

SET CODE + COLLECTOR NUMBER are more important than the card name.

Some Magic cards may use fictional languages, alternate scripts,
special frames, showcase treatments, Universes Beyond treatments,
or artwork where the title is difficult to read.

If you can clearly read the set code and collector number but cannot
read the title, name MUST be null.

Do NOT guess a card name from artwork alone.

Fields:

- name:
  Printed card title if clearly readable.
  Otherwise null.

- set_code:
  Printed set code, lowercase.
  Example: "ltc", "hoc", "2x2".
  Return null if unreadable.

- collector_number:
  Collector number only.
  Example:
  "0410/451" -> "410"
  "0095" -> "95"
  Keep letters or suffixes when they are part of the collector number.
  Return null if unreadable.

- language:
  Use a normal Scryfall language code when appropriate:
  en, ja, de, fr, it, es, pt, ru, ko, zhs, zht.

  If the card is clearly printed in a fictional language such as
  Quenya or Dwarvish, return that language name in lowercase.

  Default to "en" when uncertain.

- foil:
  Do NOT attempt to determine card finish from the image.
  Always return false.

- confidence:
  Number from 0 to 1 representing confidence in the identification
  information.

Return ONLY valid JSON matching the provided schema.
`;


/* ============================================================
   RAPID BATCH PROMPT
============================================================ */

const BATCH_PROMPT = `
You are identifying multiple Magic: The Gathering cards from ONE
contact sheet.

Each card has a clearly visible label:

CARD 1
CARD 2
CARD 3
etc.

Return exactly one result for every numbered CARD slot visible
in the image.

The slot number is extremely important.

For EACH card:

PRIORITY:

1. Read its SET CODE.
2. Read its COLLECTOR NUMBER.
3. Read its card name when possible.
4. Read its printed language when possible.

SET CODE + COLLECTOR NUMBER are more important than card name.

Do NOT identify cards from artwork alone.

Some cards may use fictional languages, alternate scripts,
Universes Beyond frames, showcase treatments or unusual artwork.

If set code and collector number are readable but the name is not,
return name as null.

Fields:

- slot:
  Number from the CARD label.

- name:
  Printed title if clearly readable.
  Otherwise null.

- set_code:
  Printed set code in lowercase.
  Otherwise null.

- collector_number:
  Printed collector number.
  Remove unnecessary leading zeroes.
  Preserve letters or suffixes when they are part of the number.
  Otherwise null.

- language:
  Use a standard Scryfall language code when appropriate:
  en, ja, de, fr, it, es, pt, ru, ko, zhs, zht.

  For clearly fictional languages such as Quenya or Dwarvish,
  return the fictional language name in lowercase.

  Default to "en" when uncertain.

- foil:
  Do NOT attempt to determine card finish.
  Always return false.

- confidence:
  Number from 0 to 1.

IMPORTANT:

The result for CARD 1 must have slot 1.
The result for CARD 2 must have slot 2.
Continue for every visible CARD label.

Do not combine cards.
Do not omit slots.
Do not invent additional slots.

Return ONLY valid JSON matching the provided schema.
`;


/* ============================================================
   JSON SCHEMAS
============================================================ */

const SINGLE_SCHEMA = {
  type:
    "object",

  properties: {

    name: {
      type:
        "string",
      nullable:
        true
    },

    set_code: {
      type:
        "string",
      nullable:
        true
    },

    collector_number: {
      type:
        "string",
      nullable:
        true
    },

    language: {
      type:
        "string",
      nullable:
        true
    },

    foil: {
      type:
        "boolean"
    },

    confidence: {
      type:
        "number"
    }
  },

  required: [
    "name",
    "set_code",
    "collector_number",
    "language",
    "foil",
    "confidence"
  ]
};


const BATCH_CARD_SCHEMA = {
  type:
    "object",

  properties: {

    slot: {
      type:
        "integer"
    },

    name: {
      type:
        "string",
      nullable:
        true
    },

    set_code: {
      type:
        "string",
      nullable:
        true
    },

    collector_number: {
      type:
        "string",
      nullable:
        true
    },

    language: {
      type:
        "string",
      nullable:
        true
    },

    foil: {
      type:
        "boolean"
    },

    confidence: {
      type:
        "number"
    }
  },

  required: [
    "slot",
    "name",
    "set_code",
    "collector_number",
    "language",
    "foil",
    "confidence"
  ]
};


const BATCH_SCHEMA = {
  type:
    "object",

  properties: {

    cards: {
      type:
        "array",

      items:
        BATCH_CARD_SCHEMA
    }
  },

  required: [
    "cards"
  ]
};


/* ============================================================
   CORS
============================================================ */

function corsHeaders(
  origin
) {

  return {

    "Access-Control-Allow-Origin":
      origin ||
      "*",

    "Access-Control-Allow-Methods":
      "POST, GET, OPTIONS",

    "Access-Control-Allow-Headers":
      "content-type, x-app-token",

    "Access-Control-Max-Age":
      "86400",

    "Vary":
      "Origin"
  };
}


/* ============================================================
   JSON RESPONSE
============================================================ */

function json(
  body,
  status,
  origin
) {

  return new Response(
    JSON.stringify(
      body
    ),
    {
      status,

      headers: {

        "Content-Type":
          "application/json",

        ...corsHeaders(
          origin
        )
      }
    }
  );
}


/* ============================================================
   WAIT
============================================================ */

function sleep(
  milliseconds
) {

  return new Promise(
    (resolve) =>
      setTimeout(
        resolve,
        milliseconds
      )
  );
}


/* ============================================================
   ARRAYBUFFER → BASE64
============================================================ */

function arrayBufferToBase64(
  buffer
) {

  const bytes =
    new Uint8Array(
      buffer
    );


  let binary =
    "";


  const chunkSize =
    0x8000;


  for (
    let i = 0;
    i < bytes.length;
    i += chunkSize
  ) {

    binary +=
      String.fromCharCode.apply(
        null,
        bytes.subarray(
          i,
          i + chunkSize
        )
      );
  }


  return btoa(
    binary
  );
}


/* ============================================================
   MODEL CHAIN
============================================================ */

function getModelChain(
  env
) {

  const models = [

    env.GEMINI_MODEL ||
      DEFAULT_PRIMARY_MODEL,

    env.GEMINI_FALLBACK_MODEL ||
      DEFAULT_FALLBACK_MODEL,

    env.GEMINI_FALLBACK_MODEL_2 ||
      DEFAULT_FALLBACK_MODEL_2
  ];


  /*
    Remove empty values and duplicates.

    This allows us to temporarily configure:

      primary = model A
      fallback = model A

    without actually calling the same fallback twice.
  */

  return [
    ...new Set(
      models
        .map(
          (model) =>
            String(
              model ||
              ""
            ).trim()
        )
        .filter(
          Boolean
        )
    )
  ];
}


/* ============================================================
   TEMPORARY / FALLBACK ELIGIBLE ERRORS
============================================================ */

function isTransientStatus(
  status
) {

  return (
    status === 429 ||
    status === 500 ||
    status === 502 ||
    status === 503 ||
    status === 504
  );
}


/*
  404 is treated differently.

  We do NOT retry the same model because it usually means
  the model ID is unavailable.

  We DO allow moving to the next model.
*/

function canFallbackFromStatus(
  status
) {

  return (
    status === 404 ||
    isTransientStatus(
      status
    )
  );
}


/* ============================================================
   SAFE JSON TEXT PARSER
============================================================ */

function parseGeminiJson(
  text
) {

  if (
    !text
  ) {

    throw new Error(
      "Gemini returned empty output."
    );
  }


  let cleaned =
    String(
      text
    ).trim();


  /*
    Structured output normally returns raw JSON,
    but this protects us if a model unexpectedly
    wraps it in a markdown code block.
  */

  if (
    cleaned.startsWith(
      "```"
    )
  ) {

    cleaned =
      cleaned
        .replace(
          /^```(?:json)?\s*/i,
          ""
        )
        .replace(
          /\s*```$/,
          ""
        )
        .trim();
  }


  return JSON.parse(
    cleaned
  );
}


/* ============================================================
   NORMALIZATION
============================================================ */

function cleanNullableString(
  value
) {

  if (
    value == null
  ) {

    return null;
  }


  const text =
    String(
      value
    ).trim();


  if (
    !text
  ) {

    return null;
  }


  return text;
}


function normalizeCollectorNumber(
  value
) {

  const text =
    cleanNullableString(
      value
    );


  if (
    !text
  ) {

    return null;
  }


  /*
    Remove leading zeroes only when followed by a digit.

    Examples:

      0095  -> 95
      0410  -> 410
      001a  -> 1a

    Does not destroy prefixes/suffixes.
  */

  return text.replace(
    /^0+(?=\d)/,
    ""
  );
}


function normalizeConfidence(
  value
) {

  const number =
    Number(
      value
    );


  if (
    !Number.isFinite(
      number
    )
  ) {

    return 0;
  }


  return Math.max(
    0,
    Math.min(
      1,
      number
    )
  );
}


function normalizeSingleResult(
  result
) {

  return {

    name:
      cleanNullableString(
        result?.name
      ),

    set_code:
      cleanNullableString(
        result?.set_code
      )
        ?.toLowerCase() ||
      null,

    collector_number:
      normalizeCollectorNumber(
        result?.collector_number
      ),

    language:
      cleanNullableString(
        result?.language
      )
        ?.toLowerCase() ||
      "en",

    /*
      Finish is controlled by the app.
      Gemini is intentionally not authoritative here.
    */
    foil:
      false,

    confidence:
      normalizeConfidence(
        result?.confidence
      )
  };
}


function normalizeBatchResult(
  result
) {

  const cards =
    Array.isArray(
      result?.cards
    )
      ? result.cards
      : [];


  const normalized =
    cards
      .map(
        (
          card,
          index
        ) => {

          const slot =
            Math.max(
              1,
              Math.round(
                Number(
                  card?.slot
                ) ||
                index + 1
              )
            );


          return {

            slot,

            name:
              cleanNullableString(
                card?.name
              ),

            set_code:
              cleanNullableString(
                card?.set_code
              )
                ?.toLowerCase() ||
              null,

            collector_number:
              normalizeCollectorNumber(
                card?.collector_number
              ),

            language:
              cleanNullableString(
                card?.language
              )
                ?.toLowerCase() ||
              "en",

            /*
              Finish is selected manually in Rapid Batch.
            */
            foil:
              false,

            confidence:
              normalizeConfidence(
                card?.confidence
              )
          };
        }
      );


  normalized.sort(
    (
      a,
      b
    ) =>
      a.slot -
      b.slot
  );


  return {
    cards:
      normalized
  };
}


/* ============================================================
   BUILD GEMINI PAYLOAD
============================================================ */

function buildGeminiPayload({
  prompt,
  schema,
  mime,
  base64
}) {

  return {

    contents: [
      {
        parts: [

          {
            text:
              prompt
          },

          {
            inline_data: {

              mime_type:
                mime,

              data:
                base64
            }
          }
        ]
      }
    ],

    generationConfig: {

      responseMimeType:
        "application/json",

      responseSchema:
        schema,

      /*
        We do not need deep reasoning for OCR-like
        identification of set code + collector number.
      */
      thinkingConfig: {
        thinkingLevel:
          "minimal"
      }
    }
  };
}


/* ============================================================
   ONE GEMINI REQUEST
============================================================ */

async function callGeminiModel({
  model,
  apiKey,
  payload,
  timeoutMs
}) {

  const controller =
    new AbortController();


  const timeout =
    setTimeout(
      () =>
        controller.abort(),
      timeoutMs
    );


  const endpoint =
    `https://generativelanguage.googleapis.com/v1beta/models/` +
    `${encodeURIComponent(model)}:generateContent?key=` +
    `${encodeURIComponent(apiKey)}`;


  try {

    let response;


    try {

      response =
        await fetch(
          endpoint,
          {
            method:
              "POST",

            headers: {
              "Content-Type":
                "application/json"
            },

            body:
              JSON.stringify(
                payload
              ),

            signal:
              controller.signal
          }
        );

    } catch (
      error
    ) {

      if (
        error?.name ===
        "AbortError"
      ) {

        return {
          ok:
            false,

          model,

          kind:
            "timeout",

          transient:
            true,

          canFallback:
            true,

          error:
            "Gemini timeout"
        };
      }


      return {
        ok:
          false,

        model,

        kind:
          "network",

        transient:
          true,

        canFallback:
          true,

        error:
          "Gemini fetch failed: " +
          (
            error?.message ||
            "network error"
          )
      };
    }


    if (
      !response.ok
    ) {

      const detail =
        await response.text();


      return {

        ok:
          false,

        model,

        kind:
          "http",

        status:
          response.status,

        transient:
          isTransientStatus(
            response.status
          ),

        canFallback:
          canFallbackFromStatus(
            response.status
          ),

        error:
          `Gemini error ${response.status}`,

        detail:
          detail.slice(
            0,
            800
          )
      };
    }


    let data;


    try {

      data =
        await response.json();

    } catch (
      error
    ) {

      return {

        ok:
          false,

        model,

        kind:
          "response",

        transient:
          true,

        canFallback:
          true,

        error:
          "Gemini returned invalid response JSON."
      };
    }


    const text =
      data
        ?.candidates
        ?.[0]
        ?.content
        ?.parts
        ?.[0]
        ?.text;


    if (
      !text
    ) {

      return {

        ok:
          false,

        model,

        kind:
          "empty",

        transient:
          true,

        canFallback:
          true,

        error:
          "No result from Gemini."
      };
    }


    let parsed;


    try {

      parsed =
        parseGeminiJson(
          text
        );

    } catch (
      error
    ) {

      return {

        ok:
          false,

        model,

        kind:
          "parse",

        transient:
          true,

        canFallback:
          true,

        error:
          "Unparseable Gemini output.",

        detail:
          String(
            text
          ).slice(
            0,
            500
          )
      };
    }


    return {

      ok:
        true,

      model,

      result:
        parsed
    };

  } finally {

    clearTimeout(
      timeout
    );
  }
}


/* ============================================================
   GEMINI FALLBACK ENGINE
============================================================ */

async function callGeminiWithFallback({
  env,
  payload,
  timeoutMs
}) {

  const models =
    getModelChain(
      env
    );


  const attempts =
    [];


  for (
    let modelIndex = 0;
    modelIndex < models.length;
    modelIndex++
  ) {

    const model =
      models[
        modelIndex
      ];


    /*
      The PRIMARY model receives one automatic retry.

      Fallback models receive one attempt each.

      This gives us:

        primary attempt
        primary retry
        fallback 1
        fallback 2

      without creating a large retry storm.
    */

    const maxAttempts =
      modelIndex === 0
        ? 2
        : 1;


    for (
      let attempt = 1;
      attempt <= maxAttempts;
      attempt++
    ) {

      const response =
        await callGeminiModel({
          model,

          apiKey:
            env.GEMINI_API_KEY,

          payload,

          timeoutMs
        });


      attempts.push({

        model,

        attempt,

        ok:
          response.ok,

        status:
          response.status ||
          null,

        kind:
          response.kind ||
          null
      });


      if (
        response.ok
      ) {

        return {

          ok:
            true,

          result:
            response.result,

          model:
            response.model,

          fallbackUsed:
            modelIndex > 0,

          attempts
        };
      }


      /*
        Do NOT blindly retry permanent errors.

        Example:

          400 bad request
          401 bad key
          403 permission problem

        A different model is unlikely to solve those.
      */

      if (
        !response.canFallback
      ) {

        return {

          ok:
            false,

          error:
            response.error,

          detail:
            response.detail ||
            null,

          status:
            response.status ||
            null,

          model:
            response.model,

          attempts
        };
      }


      /*
        Retry PRIMARY only for transient failures.

        A 404 should skip immediately to the fallback because
        retrying an unavailable model ID is pointless.
      */

      const shouldRetryPrimary =
        modelIndex === 0 &&
        attempt < maxAttempts &&
        response.transient;


      if (
        shouldRetryPrimary
      ) {

        await sleep(
          PRIMARY_RETRY_DELAY_MS
        );


        continue;
      }


      /*
        Move to the next model.
      */

      break;
    }
  }


  return {

    ok:
      false,

    error:
      "AI service is temporarily unavailable.",

    detail:
      "All configured Gemini models failed.",

    attempts
  };
}


/* ============================================================
   AUTHORIZATION
============================================================ */

function checkOrigin(
  origin,
  allowed
) {

  if (
    allowed &&
    origin &&
    origin !== allowed
  ) {

    return false;
  }


  return true;
}


/* ============================================================
   RATE LIMIT
============================================================ */

async function checkRateLimit(
  request,
  env
) {

  if (
    !env.RATE_LIMITER
  ) {

    return true;
  }


  const ip =
    request.headers.get(
      "CF-Connecting-IP"
    ) ||
    "anon";


  const result =
    await env.RATE_LIMITER.limit({
      key:
        ip
    });


  return !!result.success;
}


/* ============================================================
   READ IMAGE
============================================================ */

async function readImage(
  request
) {

  const buffer =
    await request.arrayBuffer();


  if (
    !buffer.byteLength ||
    buffer.byteLength >
      MAX_IMAGE_BYTES
  ) {

    throw new Error(
      "bad image size"
    );
  }


  return {

    buffer,

    base64:
      arrayBufferToBase64(
        buffer
      ),

    mime:
      request.headers.get(
        "Content-Type"
      ) ||
      "image/jpeg"
  };
}


/* ============================================================
   SINGLE IDENTIFICATION
============================================================ */

async function identifySingle({
  env,
  image
}) {

  const payload =
    buildGeminiPayload({

      prompt:
        SINGLE_PROMPT,

      schema:
        SINGLE_SCHEMA,

      mime:
        image.mime,

      base64:
        image.base64
    });


  const response =
    await callGeminiWithFallback({

      env,

      payload,

      timeoutMs:
        SINGLE_TIMEOUT_MS
    });


  if (
    !response.ok
  ) {

    return response;
  }


  return {

    ...response,

    result:
      normalizeSingleResult(
        response.result
      )
  };
}


/* ============================================================
   BATCH IDENTIFICATION
============================================================ */

async function identifyBatch({
  env,
  image
}) {

  const payload =
    buildGeminiPayload({

      prompt:
        BATCH_PROMPT,

      schema:
        BATCH_SCHEMA,

      mime:
        image.mime,

      base64:
        image.base64
    });


  const response =
    await callGeminiWithFallback({

      env,

      payload,

      timeoutMs:
        BATCH_TIMEOUT_MS
    });


  if (
    !response.ok
  ) {

    return response;
  }


  return {

    ...response,

    result:
      normalizeBatchResult(
        response.result
      )
  };
}


/* ============================================================
   WORKER
============================================================ */

export default {

  async fetch(
    request,
    env
  ) {

    const url =
      new URL(
        request.url
      );


    const origin =
      request.headers.get(
        "Origin"
      );


    const allowed =
      env.ALLOWED_ORIGIN ||
      "";


    const responseOrigin =
      allowed ||
      origin;


    /* ========================================================
       CORS PREFLIGHT
    ======================================================== */

    if (
      request.method ===
      "OPTIONS"
    ) {

      return new Response(
        null,
        {
          status:
            204,

          headers:
            corsHeaders(
              responseOrigin
            )
        }
      );
    }


    /* ========================================================
       HEALTH
    ======================================================== */

    if (
      url.pathname ===
        "/health" &&
      request.method ===
        "GET"
    ) {

      const models =
        getModelChain(
          env
        );


      return json(
        {

          ok:
            true,

          endpoints: [
            "/identify",
            "/identify-batch"
          ],

          model:
            models[0] ||
            null,

          models: {

            primary:
              models[0] ||
              null,

            fallbacks:
              models.slice(
                1
              )
          },

          ratelimit:
            !!env.RATE_LIMITER
        },

        200,

        responseOrigin
      );
    }


    /* ========================================================
       VALID ROUTES
    ======================================================== */

    const isSingle =
      url.pathname ===
        "/identify";


    const isBatch =
      url.pathname ===
        "/identify-batch";


    if (
      request.method !==
        "POST" ||
      (
        !isSingle &&
        !isBatch
      )
    ) {

      return json(
        {
          error:
            "not found"
        },

        404,

        responseOrigin
      );
    }


    /* ========================================================
       ORIGIN CHECK
    ======================================================== */

    if (
      !checkOrigin(
        origin,
        allowed
      )
    ) {

      return json(
        {
          error:
            "forbidden origin"
        },

        403,

        allowed
      );
    }


    /* ========================================================
       APP TOKEN
    ======================================================== */

    if (
      !env.APP_TOKEN ||
      request.headers.get(
        "x-app-token"
      ) !== env.APP_TOKEN
    ) {

      return json(
        {
          error:
            "unauthorized"
        },

        401,

        responseOrigin
      );
    }


    /* ========================================================
       RATE LIMIT
    ======================================================== */

    try {

      const allowedByRateLimit =
        await checkRateLimit(
          request,
          env
        );


      if (
        !allowedByRateLimit
      ) {

        return json(
          {
            error:
              "rate limited — too many scans, wait a moment and retry"
          },

          429,

          responseOrigin
        );
      }

    } catch (
      error
    ) {

      /*
        Rate limiter failure should not make the entire app
        unusable. Gemini quota still acts as a backstop.
      */

      console.error(
        "Rate limiter error:",
        error
      );
    }


    /* ========================================================
       GEMINI CONFIG
    ======================================================== */

    if (
      !env.GEMINI_API_KEY
    ) {

      return json(
        {
          error:
            "server not configured (no GEMINI_API_KEY)"
        },

        500,

        responseOrigin
      );
    }


    /* ========================================================
       IMAGE
    ======================================================== */

    let image;


    try {

      image =
        await readImage(
          request
        );

    } catch (
      error
    ) {

      return json(
        {
          error:
            "bad image size"
        },

        400,

        responseOrigin
      );
    }


    /* ========================================================
       IDENTIFY
    ======================================================== */

    let result;


    try {

      result =
        isBatch
          ? await identifyBatch({
              env,
              image
            })
          : await identifySingle({
              env,
              image
            });

    } catch (
      error
    ) {

      console.error(
        "Identification error:",
        error
      );


      return json(
        {
          error:
            "AI identification failed",

          detail:
            error?.message ||
            "unknown error"
        },

        502,

        responseOrigin
      );
    }


    /* ========================================================
       ALL MODELS FAILED
    ======================================================== */

    if (
      !result.ok
    ) {

      /*
        Permanent configuration/API errors retain 502.

        Temporary availability failures return 503 so we can
        distinguish them later in the frontend if desired.
      */

      const hasTemporaryFailure =
        result.attempts
          ?.some(
            (attempt) =>
              attempt.kind ===
                "timeout" ||
              attempt.kind ===
                "network" ||
              isTransientStatus(
                attempt.status
              )
          );


      const status =
        hasTemporaryFailure
          ? 503
          : 502;


      return json(
        {

          error:
            result.error ||
            "AI identification failed",

          detail:
            result.detail ||
            null,

          attempts:
            result.attempts ||
            []
        },

        status,

        responseOrigin
      );
    }


    /* ========================================================
       SUCCESS
    ======================================================== */

    return json(
      {

        ok:
          true,

        result:
          result.result,

        /*
          Debugging information.

          Existing frontend ignores these fields,
          so this does not break Single Scan or Rapid Batch.
        */

        model:
          result.model,

        fallback_used:
          !!result.fallbackUsed,

        attempts:
          result.attempts
      },

      200,

      responseOrigin
    );
  }
};